In [145]:
import pandas as pd
import json

pd.set_option('display.max_info_columns', 200)

In [146]:
data = pd.read_csv('PSB/data/finances.csv')
inns = data['inn']
data['data'] = data['data'].apply(json.loads)

In [147]:
df_expanded = pd.json_normalize(data['data'])
df_expanded.columns = [col.replace('.', '_') for col in df_expanded.columns]

In [148]:
df_expanded = pd.concat([inns, df_expanded], axis=1)
# df_expanded.to_csv("PSB/data/finances_v02.csv")

In [ ]:
# patterns_to_keep_v03_01 = ["1300", "1400", "1500", "1530", '1600', '1700', "2100", "2110", "2200", "2400","3221", "3311", "3500"]
patterns_to_keep_v03_01 = ["inn", "1300", "2200", "2400"]
filtered_columns_v03_01 = [col for col in df_expanded.columns if any(str(num) in str(col) for num in patterns_to_keep_v03_01)]
df_filtered_v03_01 = df_expanded[filtered_columns_v03_01]
df_filtered_v03_01.head()
df_filtered_v03_01.to_csv("PSB/data/finances_v03_01.csv")
new_columns = {}
for col in df_filtered_v03_01.columns:
    if col == "inn":
        new_columns[col] = "inn"
        continue
    parts = col.split('_')
    # print(parts)
    if parts[3][3] == "О":
        new_name = f"{parts[1]}_{parts[2]}_0"
    else:
        new_name = f"{parts[1]}_{parts[2]}_1"
    new_columns[col] = new_name
df_filtered_v03_01 = df_filtered_v03_01.rename(columns=new_columns)
sorted_columns = sorted(new_columns.values(), key=lambda x: x.split('_')[0])
sorted_columns.insert(0, "inn")
df_filtered_v03_01 = df_filtered_v03_01[sorted_columns] 

# df_filtered_v03_01.to_csv("PSB/datafinances_v03_01.csv")
# df_filtered_v03_01.head()

,inn,2012_1300_0,2012_1300_1,2012_2200_0,2012_2200_1,2012_2400_0,2012_2400_1,2013_1300_0,2013_1300_1,2013_2200_0,...,2024_1300_0,2024_1300_1,2024_1300_1,2024_1300_1,2024_1300_1,2024_2200_0,2024_2200_1,2024_2400_0,2024_2400_1,inn
0,1001098784,12828000.0,12642000.0,8768000.0,14768000.0,186000.0,2792000.0,14788000.0,17062000.0,27861000.0,...,-296703000.0,-275740000.0,-238644000.0,-275740000.0,-238644000.0,-13412000.0,-18294000.0,-8904000.0,-37095000.0,1001098784
1,1001028755,14000.0,-1650000.0,0.0,0.0,1664000.0,-1660000.0,NaN,NaN,NaN,...,69173000.0,69080000.0,73299000.0,69080000.0,73299000.0,15572000.0,9205000.0,93000.0,-4219000.0,1001028755
2,1001095007,8440000.0,8469000.0,0.0,0.0,971000.0,635000.0,7624000.0,8440000.0,-59000.0,...,16949000.0,17473000.0,18429000.0,17473000.0,18429000.0,NaN,NaN,1085000.0,308000.0,1001095007
3,1001001390,41342000.0,83328000.0,-31005000.0,49058000.0,-41925000.0,-68306000.0,53940000.0,41370000.0,47213000.0,...,236864000.0,223839000.0,265575000.0,223839000.0,265575000.0,12110000.0,-103698000.0,900000.0,-100498000.0,1001001390
4,1001004095,28304000.0,23636000.0,0.0,0.0,5736000.0,4673000.0,30185000.0,28304000.0,4598000.0,...,169797000.0,171235000.0,171441000.0,171235000.0,171441000.0,5558000.0,11455000.0,2183000.0,7243000.0,1001004095

In [ ]:
filtered_columns = [col for col in df_filtered_v03_01.columns 
                   if (len(col.split('_')) == 3  
                   and col.split('_')[0].isdigit() 
                   and int(col.split('_')[0]) >= 2020) or col == "inn"]
df_filtered_v03_02 = df_filtered_v03_01[filtered_columns]
df_filtered_v03_02 = df_filtered_v03_02.iloc[:, 1:]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 108 columns):
 #    Column       Non-Null Count  Dtype
---   ------       --------------  -----
 0    inn          15000 non-null  int64
 1    2020_1300_0  14999 non-null  float64
 2    2020_1300_1  14906 non-null  float64
 3    2020_1300_1  14592 non-null  float64
 4    2020_1300_1  14906 non-null  float64
 5    2020_1300_1  14592 non-null  float64
 6    2020_1300_1  14906 non-null  float64
 7    2020_1300_1  14592 non-null  float64
 8    2020_1300_1  14906 non-null  float64
 9    2020_1300_1  14592 non-null  float64
 10   2020_1300_1  14906 non-null  float64
 11   2020_1300_1  14592 non-null  float64
 12   2020_1300_1  14906 non-null  float64
 13   2020_1300_1  14592 non-null  float64
 14   2020_1300_1  14906 non-null  float64
 15   2020_1300_1  14592 non-null  float64
 16   2020_1300_1  14906 non-null  float64
 17   2020_1300_1  14592 non-null  float64
 18   2020_2200_0  11028 non-null  float64
 19   2020_2200_1  10802 non-null  float64
 20   2020_2400_0  14992 non-null  float64
 21   2020_2400_1  14992 non-null  float64
 22   2021_1300_0  14979 non-null  float64
 23   2021_1300_1  14969 non-null  float64
 24   2021_1300_1  14875 non-null  float64
 25   2021_1300_1  14969 non-null  float64
 26   2021_1300_1  14875 non-null  float64
 27   2021_1300_1  14969 non-null  float64
 28   2021_1300_1  14875 non-null  float64
 29   2021_1300_1  14969 non-null  float64
 30   2021_1300_1  14875 non-null  float64
 31   2021_1300_1  14969 non-null  float64
 32   2021_1300_1  14875 non-null  float64
 33   2021_1300_1  14969 non-null  float64
 34   2021_1300_1  14875 non-null  float64
 35   2021_1300_1  14969 non-null  float64
 36   2021_1300_1  14875 non-null  float64
 37   2021_1300_1  14969 non-null  float64
 38   2021_1300_1  14875 non-null  float64
 39   2021_2200_0  10744 non-null  float64
 40   2021_2200_1  10722 non-null  float64
 41   2021_2400_0  14968 non-null  float64
 42   2021_2400_1  14968 non-null  float64
 43   2022_1300_0  14968 non-null  float64
 44   2022_1300_1  14957 non-null  float64
 45   2022_1300_1  14939 non-null  float64
 46   2022_1300_1  14957 non-null  float64
 47   2022_1300_1  14939 non-null  float64
 48   2022_1300_1  14957 non-null  float64
 49   2022_1300_1  14939 non-null  float64
 50   2022_1300_1  14957 non-null  float64
 51   2022_1300_1  14939 non-null  float64
 52   2022_1300_1  14957 non-null  float64
 53   2022_1300_1  14939 non-null  float64
 54   2022_1300_1  14957 non-null  float64
 55   2022_1300_1  14939 non-null  float64
 56   2022_1300_1  14957 non-null  float64
 57   2022_1300_1  14939 non-null  float64
 58   2022_1300_1  14957 non-null  float64
 59   2022_1300_1  14939 non-null  float64
 60   2022_2200_0  10643 non-null  float64
 61   2022_2200_1  10622 non-null  float64
 62   2022_2400_0  14956 non-null  float64
 63   2022_2400_1  14956 non-null  float64
 64   2023_1300_0  14997 non-null  float64
 65   2023_1300_1  14988 non-null  float64
 66   2023_1300_1  14974 non-null  float64
 67   2023_1300_1  14988 non-null  float64
 68   2023_1300_1  14974 non-null  float64
 69   2023_1300_1  14988 non-null  float64
 70   2023_1300_1  14974 non-null  float64
 71   2023_1300_1  14988 non-null  float64
 72   2023_1300_1  14974 non-null  float64
 73   2023_1300_1  14988 non-null  float64
 74   2023_1300_1  14974 non-null  float64
 75   2023_1300_1  14988 non-null  float64
 76   2023_1300_1  14974 non-null  float64
 77   2023_1300_1  14988 non-null  float64
 78   2023_1300_1  14974 non-null  float64
 79   2023_1300_1  14988 non-null  float64
 80   2023_1300_1  14974 non-null  float64
 81   2023_2200_0  10634 non-null  float64
 82   2023_2200_1  10617 non-null  float64
 83   2023_2400_0  14996 non-null  float64
 84   2023_2400_1  14996 non-null  float64
 85   2024_1300_0  13954 non-null  float64
 86   2024_1300_1  13945 non-null  float64
 87   2024_1300_1  13938 non-null  float64
 88   2024_1300_1  13945 non-null  float64
 89   2024_1300_1  13938 non-null  float64
 90   2024_1300_1  13945 non-null  float64
 91   2024_1300_1  13938 non-null  float64
 92   2024_1300_1  13945 non-null  float64
 93   2024_1300_1  13938 non-null  float64
 94   2024_1300_1  13945 non-null  float64
 95   2024_1300_1  13938 non-null  float64
 96   2024_1300_1  13945 non-null  float64
 97   2024_1300_1  13938 non-null  float64
 98   2024_1300_1  13945 non-null  float64
 99   2024_1300_1  13938 non-null  float64
 100  2024_1300_1  13945 non-null  float64
 101  2024_1300_1  13938 non-null  float64
 102  2024_2200_0  9806 non-null   float64
 103  2024_2200_1  9792 non-null   float64
 104  2024_2400_0  13922 non-null  float64
 105  2024_2400_1  13922 non-null  float64
 106  inn          15000 non-null  int64
 107  inn          15000 non-null  int64
dtypes: float64(105), int64(3)
memory usage: 12.4 MB

In [170]:
df_filtered_v03_02 = df_filtered_v03_02.fillna(df_filtered_v03_02.median(axis=0))
df_filtered_v03_02.info()
df_filtered_v03_02.to_csv("PSB/data/finances_final.csv")
df_filtered_v03_02.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 108 columns):
 #    Column       Non-Null Count  Dtype
---   ------       --------------  -----
 0    inn          15000 non-null  int64
 1    2020_1300_0  15000 non-null  float64
 2    2020_1300_1  15000 non-null  float64
 3    2020_1300_1  15000 non-null  float64
 4    2020_1300_1  15000 non-null  float64
 5    2020_1300_1  15000 non-null  float64
 6    2020_1300_1  15000 non-null  float64
 7    2020_1300_1  15000 non-null  float64
 8    2020_1300_1  15000 non-null  float64
 9    2020_1300_1  15000 non-null  float64
 10   2020_1300_1  15000 non-null  float64
 11   2020_1300_1  15000 non-null  float64
 12   2020_1300_1  15000 non-null  float64
 13   2020_1300_1  15000 non-null  float64
 14   2020_1300_1  15000 non-null  float64
 15   2020_1300_1  15000 non-null  float64
 16   2020_1300_1  15000 non-null  float64
 17   2020_1300_1  15000 non-null  float64
 18   2020_2200_0  15000 non-null  float64
 19   2020_2200_1  15000 non-null  float64
 20   2020_2400_0  15000 non-null  float64
 21   2020_2400_1  15000 non-null  float64
 22   2021_1300_0  15000 non-null  float64
 23   2021_1300_1  15000 non-null  float64
 24   2021_1300_1  15000 non-null  float64
 25   2021_1300_1  15000 non-null  float64
 26   2021_1300_1  15000 non-null  float64
 27   2021_1300_1  15000 non-null  float64
 28   2021_1300_1  15000 non-null  float64
 29   2021_1300_1  15000 non-null  float64
 30   2021_1300_1  15000 non-null  float64
 31   2021_1300_1  15000 non-null  float64
 32   2021_1300_1  15000 non-null  float64
 33   2021_1300_1  15000 non-null  float64
 34   2021_1300_1  15000 non-null  float64
 35   2021_1300_1  15000 non-null  float64
 36   2021_1300_1  15000 non-null  float64
 37   2021_1300_1  15000 non-null  float64
 38   2021_1300_1  15000 non-null  float64
 39   2021_2200_0  15000 non-null  float64
 40   2021_2200_1  15000 non-null  float64
 41   2021_2400_0  15000 non-null  float64
 42   2021_2400_1  15000 non-null  float64
 43   2022_1300_0  15000 non-null  float64
 44   2022_1300_1  15000 non-null  float64
 45   2022_1300_1  15000 non-null  float64
 46   2022_1300_1  15000 non-null  float64
 47   2022_1300_1  15000 non-null  float64
 48   2022_1300_1  15000 non-null  float64
 49   2022_1300_1  15000 non-null  float64
 50   2022_1300_1  15000 non-null  float64
 51   2022_1300_1  15000 non-null  float64
 52   2022_1300_1  15000 non-null  float64
 53   2022_1300_1  15000 non-null  float64
 54   2022_1300_1  15000 non-null  float64
 55   2022_1300_1  15000 non-null  float64
 56   2022_1300_1  15000 non-null  float64
 57   2022_1300_1  15000 non-null  float64
 58   2022_1300_1  15000 non-null  float64
 59   2022_1300_1  15000 non-null  float64
 60   2022_2200_0  15000 non-null  float64
 61   2022_2200_1  15000 non-null  float64
 62   2022_2400_0  15000 non-null  float64
 63   2022_2400_1  15000 non-null  float64
 64   2023_1300_0  15000 non-null  float64
 65   2023_1300_1  15000 non-null  float64
 66   2023_1300_1  15000 non-null  float64
 67   2023_1300_1  15000 non-null  float64
 68   2023_1300_1  15000 non-null  float64
 69   2023_1300_1  15000 non-null  float64
 70   2023_1300_1  15000 non-null  float64
 71   2023_1300_1  15000 non-null  float64
 72   2023_1300_1  15000 non-null  float64
 73   2023_1300_1  15000 non-null  float64
 74   2023_1300_1  15000 non-null  float64
 75   2023_1300_1  15000 non-null  float64
 76   2023_1300_1  15000 non-null  float64
 77   2023_1300_1  15000 non-null  float64
 78   2023_1300_1  15000 non-null  float64
 79   2023_1300_1  15000 non-null  float64
 80   2023_1300_1  15000 non-null  float64
 81   2023_2200_0  15000 non-null  float64
 82   2023_2200_1  15000 non-null  float64
 83   2023_2400_0  15000 non-null  float64
 84   2023_2400_1  15000 non-null  float64
 85   2024_1300_0  15000 non-null  float64
 86   2024_1300_1  15000 non-null  float64
 87   2024_1300_1  15000 non-null  float64
 88   2024_1300_1  15000 non-null  float64
 89   2024_1300_1  15000 non-null  float64
 90   2024_1300_1  15000 non-null  float64
 91   2024_1300_1  15000 non-null  float64
 92   2024_1300_1  15000 non-null  float64
 93   2024_1300_1  15000 non-null  float64
 94   2024_1300_1  15000 non-null  float64
 95   2024_1300_1  15000 non-null  float64
 96   2024_1300_1  15000 non-null  float64
 97   2024_1300_1  15000 non-null  float64
 98   2024_1300_1  15000 non-null  float64
 99   2024_1300_1  15000 non-null  float64
 100  2024_1300_1  15000 non-null  float64
 101  2024_1300_1  15000 non-null  float64
 102  2024_2200_0  15000 non-null  float64
 103  2024_2200_1  15000 non-null  float64
 104  2024_2400_0  15000 non-null  float64
 105  2024_2400_1  15000 non-null  float64
 106  inn          15000 non-null  int64
 107  inn          15000 non-null  int64
dtypes: float64(105), int64(3)
memory usage: 12.4 MB

,inn,2020_1300_0,2020_1300_1,2020_1300_1,2020_1300_1,2020_1300_1,2020_1300_1,2020_1300_1,2020_1300_1,2020_1300_1,...,2024_1300_1,2024_1300_1,2024_1300_1,2024_1300_1,2024_2200_0,2024_2200_1,2024_2400_0,2024_2400_1,inn,inn
0,1001098784,-143410000.0,-69608000.0,-57962000.0,-69608000.0,-57962000.0,-69608000.0,-57962000.0,-69608000.0,-57962000.0,...,-275740000.0,-238644000.0,-275740000.0,-238644000.0,-13412000.0,-18294000.0,-8904000.0,-37095000.0,1001098784,1001098784
1,1001028755,65096000.0,59609000.0,63640000.0,59609000.0,63640000.0,59609000.0,63640000.0,59609000.0,63640000.0,...,69080000.0,73299000.0,69080000.0,73299000.0,15572000.0,9205000.0,93000.0,-4219000.0,1001028755,1001028755
2,1001095007,19703000.0,15733000.0,14769000.0,15733000.0,14769000.0,15733000.0,14769000.0,15733000.0,14769000.0,...,17473000.0,18429000.0,17473000.0,18429000.0,20824500.0,23153500.0,1085000.0,308000.0,1001095007,1001095007
3,1001001390,197294000.0,188970000.0,370802000.0,188970000.0,370802000.0,188970000.0,370802000.0,188970000.0,370802000.0,...,223839000.0,265575000.0,223839000.0,265575000.0,12110000.0,-103698000.0,900000.0,-100498000.0,1001001390,1001001390
4,1001004095,54905000.0,25644000.0,20197000.0,25644000.0,20197000.0,25644000.0,20197000.0,25644000.0,20197000.0,...,171235000.0,171441000.0,171235000.0,171441000.0,5558000.0,11455000.0,2183000.0,7243000.0,1001004095,1001004095